**INITIAL VALIDATION**

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("../data/Palo Alto Networks.csv")

In [3]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [17]:
df.shape

(1470, 31)

In [18]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='str')

In [19]:
df['Attrition'].value_counts()

Attrition
0    1233
1     237
Name: count, dtype: int64

In [20]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [22]:
for col in ['Department','JobRole','OverTime','BusinessTravel']:
    print(col,df[col].unique())

Department <StringArray>
['Sales', 'Research & Development', 'Human Resources']
Length: 3, dtype: str
JobRole <StringArray>
[          'Sales Executive',        'Research Scientist',
     'Laboratory Technician',    'Manufacturing Director',
 'Healthcare Representative',                   'Manager',
      'Sales Representative',         'Research Director',
           'Human Resources']
Length: 9, dtype: str
OverTime <StringArray>
['Yes', 'No']
Length: 2, dtype: str
BusinessTravel <StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel']
Length: 3, dtype: str

In [23]:
df.duplicated().sum()

np.int64(0)

In [40]:
attrition_rate=round((df[df['Attrition']==1].shape[0])*100/df['Attrition'].shape[0],2)

In [41]:
attrition_rate

16.12

In [48]:
df['Attrition'].value_counts()

Attrition
0    1233
1     237
Name: count, dtype: int64

In [49]:
labels={0:'Retained',1:'Exited'}

In [55]:
attrition_summary = df['Attrition'].map(labels).value_counts().reset_index()

In [56]:
attrition_summary

  Attrition  count
0  Retained   1233
1    Exited    237

In [57]:
attrition_summary.columns=['AttritionStatus','EmployeeCount']

In [58]:
attrition_summary

  AttritionStatus  EmployeeCount
0        Retained           1233
1          Exited            237

In [76]:
import plotly.express as px

In [80]:
import plotly.io as pio
pio.renderers.default = 'browser'

In [100]:
fig=px.bar(attrition_summary,x='AttritionStatus',y='EmployeeCount',color='AttritionStatus',title='Employee Attrition Distribution')
fig.show()

In [89]:
department_attrition=round(df['Attrition'].groupby(df['Department']).mean()*100,2).sort_values(ascending=False).reset_index()

In [90]:
department_attrition.columns=['Department','AttritionRate']

In [91]:
department_attrition

               Department  AttritionRate
0                   Sales          20.63
1         Human Resources          19.05
2  Research & Development          13.84

In [101]:
fig=px.bar(department_attrition,x='AttritionRate',y='Department',color='Department',title='Department Attrition Rate (%)')
fig.update_layout(xaxis_title='Attrition Rate (%)',showlegend=False)
fig.show()

In [102]:
job_role_attrition=round(df['Attrition'].groupby(df['JobRole']).mean()*100,2).sort_values(ascending=False).reset_index()

In [103]:
job_role_attrition

                     JobRole  Attrition
0       Sales Representative      39.76
1      Laboratory Technician      23.94
2            Human Resources      23.08
3            Sales Executive      17.48
4         Research Scientist      16.10
5     Manufacturing Director       6.90
6  Healthcare Representative       6.87
7                    Manager       4.90
8          Research Director       2.50

In [104]:
job_role_attrition.columns=['JobRole','AttritionRate']

In [108]:
fig=px.bar(job_role_attrition,x='AttritionRate',y='JobRole',color='JobRole',title='Job Role Attrition Rate (%)')
fig.update_layout(xaxis_title='Attrition Rate (%)',showlegend=False)
fig.show()

In [109]:
age_bins=[18,25,35,45,55,65]
age_labels=['18-25','26-35','36-45','46-55','56-65']

In [110]:
df['AgeGroup']=pd.cut(df['Age'],bins=age_bins,labels=age_labels,include_lowest=True)

In [113]:
df['AgeGroup'].value_counts().sort_index()

AgeGroup
18-25    123
26-35    606
36-45    468
46-55    226
56-65     47
Name: count, dtype: int64

In [118]:
age_wise_attrition=round(df['Attrition'].groupby(df['AgeGroup']).mean()*100,2).reset_index()

In [120]:
age_wise_attrition.columns=['AgeGroup','Attrition Rate']

In [121]:
age_wise_attrition

  AgeGroup  Attrition Rate
0    18-25           35.77
1    26-35           19.14
2    36-45            9.19
3    46-55           11.50
4    56-65           17.02

In [123]:
fig = px.bar(age_wise_attrition,x='AgeGroup',y='Attrition Rate',color='AgeGroup',title='Attrition Rate by Age Group (%)')
fig.update_layout(yaxis_title='Attrition Rate (%)',showlegend=False)
fig.show()

In [126]:
attrition_by_gender=round(df['Attrition'].groupby(df['Gender']).mean()*100,2).reset_index()

In [125]:
attrition_by_gender

Gender
Female    14.80
Male      17.01
Name: Attrition, dtype: float64

In [129]:
tenure_bins=[-1,2,5,10,float('inf')]
tenure_labels=['0-2 Early tenure','3-5 Developing','6-10 Established','11+ Long tenure']
df['TenureGroup']=pd.cut(
    df['YearsAtCompany'],
    bins=tenure_bins,
    labels=tenure_labels
)

In [137]:
attrition_by_tenure=round(df['Attrition'].groupby(df['TenureGroup']).mean()*100,2).reset_index()

In [138]:
attrition_by_tenure

        TenureGroup  Attrition
0  0-2 Early tenure      29.82
1    3-5 Developing      13.82
2  6-10 Established      12.28
3   11+ Long tenure       8.13

In [139]:
attrition_by_tenure.columns=['Tenure Group','Attrition Rate (%)']

In [143]:
fig=px.figsize=(10,10)
fig=px.bar(attrition_by_tenure,x='Tenure Group',y='Attrition Rate (%)',color='Tenure Group',title='Attrition Rate by Tenure')
fig.update_layout(showlegend=False)
fig.show()

In [144]:
df['OverTime'].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [145]:
attrition_by_overtime=round(df['Attrition'].groupby(df['OverTime']).mean()*100,2).sort_values(ascending=False).reset_index()

In [147]:
attrition_by_overtime.columns=['Over Time','Attrition Rate (%)']

In [148]:
attrition_by_overtime

  Over Time  Attrition Rate (%)
0       Yes               30.53
1        No               10.44

In [153]:
px.figsize=(10,10)
fig=px.bar(attrition_by_overtime,x='Over Time',y='Attrition Rate (%)',color='Over Time',title='Attrition Rate by Over Time')
fig.update_layout(showlegend=False)
fig.show()

In [ ]:
df['BusinessTravel'].value_counts().

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [155]:
attrition_by_business_travel=round(df['Attrition'].groupby(df['BusinessTravel']).mean()*100,2).sort_values(ascending=False).reset_index()

In [157]:
attrition_by_business_travel.columns=['Business Travel','Attrition Rate (%)']

In [159]:
attrition_by_business_travel

     Business Travel  Attrition Rate (%)
0  Travel_Frequently               24.91
1      Travel_Rarely               14.96
2         Non-Travel                8.00

In [160]:
px.figsize=(10,10)
fig=px.bar(attrition_by_business_travel,x='Business Travel',y='Attrition Rate (%)',color='Business Travel',title='Attrition Rate by Business Travel')
fig.update_layout(showlegend=False)
fig.show()

In [161]:
df['DistanceFromHome'].value_counts()

DistanceFromHome
2     211
1     208
10     86
9      85
3      84
7      84
8      80
5      65
4      64
6      59
16     32
11     29
24     28
23     27
29     27
15     26
18     26
26     25
25     25
20     25
28     23
19     22
14     21
12     20
17     20
22     19
13     19
21     18
27     12
Name: count, dtype: int64

In [162]:
distance_bins=[-1,5,10,20,float('inf')]
distance_labels=['0-5','6-10','11-20','21+']

In [163]:
df['DistanceGroup']=pd.cut(
    df['DistanceFromHome'],
    bins=distance_bins,
    labels=distance_labels
)

In [165]:
df['DistanceGroup'].value_counts().sort_index()

DistanceGroup
0-5      632
6-10     394
11-20    240
21+      204
Name: count, dtype: int64

In [166]:
attrition_by_distance=round(df['Attrition'].groupby(df['DistanceGroup']).mean()*100,2).reset_index()

In [168]:
attrition_by_distance.columns=['Distance Group','Attrition Rate (%)']

In [169]:
attrition_by_distance

  Distance Group  Attrition Rate (%)
0            0-5               13.77
1           6-10               14.47
2          11-20               20.00
3            21+               22.06

In [170]:
px.figsize=(10,10)
fig=px.bar(attrition_by_distance,x='Distance Group',y='Attrition Rate (%)',color='Distance Group',title='Attrition Rate by Distance from Home')
fig.update_layout(showlegend=False)
fig.show()